all:  ucp timeprog numero comunication ts

ucp:
	clang -o ucp ucp.c

timeprog: 
	clang -o timeprog timeprog.c

numero:
	clang -o numero numero.c

comunication:
	clang -o comunication comunication.c

ts:
	clang -o ts ts.c

clean:
	rm ucp timeprog numero comunication ts
