all:  ucp timeprog numero comunication

ucp:
	clang -o ucp ucp.c

timeprog: 
	clang -o timeprog timeprog.c

numero:
	clang -o numero numero.c

comunication:
	clang -o comunication comunication.c

clean:
	rm ucp timeprog numero comunication