all: clean copy

clean:
	rm /usr/src/minix/kernel/proc.h
	rm /usr/src/minix/kernel/priv.h
	rm /usr/src/minix/servers/is/dmp.c
	rm /usr/src/minix/servers/is/dmp_pm.c

copy:
	cp proc.h /usr/src/minix/kernel/proc.h
	cp priv.h /usr/src/minix/kernel/priv.h
	cp dmp.c /usr/src/minix/servers/is/dmp.c
	cp dmp_pm.c /usr/src/minix/servers/is/dmp_pm.c